// lang
export const CHANGE_LANG = "CHANGE_LANG";

// user
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_FREELANCER = "UPDATE_FREELANCER";

export const UPDATE_SPINNER_STATUS = "UPDATE_SPINNER_STATUS";
export const CLEAR_SPINNER_STATUS = "CLEAR_SPINNER_STATUS";
